image: kroniak/ssh-client:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
  - shell
  script:
  - ./build.sh

test:
  stage: test
  tags:
    - shell
  script:
  - ./test_e2e.sh

deploy:
  stage: deploy
  script:
    - ./install.sh

