image: kroniak/ssh-client:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
  - shell
  script:
  - ./build.sh

test:
  stage: test
  tags:
    - shell
  script:
  - ./test_e2e.sh

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser heoh\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ./install.sh

