image: docker:stable

stages:
  - build
  - e2e test

services:
  - java:8

build:
  stage: build
  tags:
  - shell
  script:
  - ./build.sh

e2e test:
  stage: test
  tags:
    - shell
  script:
  - ./test_e2e.sh
